server {
    listen 80;
    listen [::]:80;
    server_name everechoai.com www.everechoai.com;

    root /opt/everecho-landing;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
